# Generated by Django 4.2.9 on 2025-05-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_avatar'),
        ('myauth', '0002_profile_birth_date_profile_location'),
    ]

    operations = [
    ]
