# Generated by Django 4.2.9 on 2025-05-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_merge_20250525_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
